image: marcopeg/gitpod-workspace-hasura:1.3.0

tasks:
  - name: Hasura
    command: bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4000/ping)" != "200" ]]; do sleep 1; done' && hasura_start
    openIn: right
  - name: Migrations
    before: cd hasura
    init: bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/v1/version)" != "200" ]]; do sleep 1; done' && hasura migrate apply && hasura metadata apply && hasura seeds apply
    openIn: right
  - name: Backend
    before: cd backend
    init: npm install
    command: HASURA_ENDPOINT=$(gp url 8080) npm start
    openIn: right
  - name: Frontend
    before: cd frontend
    init: npm install
    command: REACT_APP_HASURA_URL=$(gp url 8080) npm start
    openIn: right

ports:
  - port: 5432
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
  - port: 4000
    onOpen: ignore
  - port: 8008
    onOpen: ignore
