image: marcopeg/gitpod-workspace-hasura

tasks:
  - name: Hasura
    command: hasura_start
    openIn: right
  - name: Frontend
    before: cd frontend
    init: yarn install
    command: REACT_APP_HASURA_URL=$(gp url 8080) yarn start
    openIn: right
  - name: Backend
    before: cd backend
    init: yarn install
    command: HASURA_ENDPOINT=$(gp url 8080) yarn start
    openIn: right
  - name: Seed
    before: cd seed
    init: yarn install
    command: HASURA_ENDPOINT=$(gp url 8080) yarn start
    openIn: right

ports:
  - port: 5432
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser
  - port: 4000
    onOpen: ignore
