version: "2.1"
services:
  ###
  ### APPLICATION
  ###

  backend:
    container_name: backend
    image: node:12.2-alpine
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    volumes:
      - ./docker-data/backend/node_modules:/usr/src/app/node_modules:cached
      - ./backend/package.json:/usr/src/app/package.json:delegated
      - ./backend/package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./backend/index.js:/usr/src/app/index.js:delegated
      - ./backend/feature-capitalize.js:/usr/src/app/feature-capitalize.js:delegated
    environment:
      PORT: 4000
      HASURA_ENDPOINT: http://hasura:8080
      HASURA_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0MTYyMzkwMjIsImV4cCI6NzUxNjIzOTAyMiwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbImJhY2tlbmQiXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoiYmFja2VuZCJ9fQ.epNPoNjKtvmgompkJnb4my7kZYF-muUu_HzKSeu6siM
    working_dir: /usr/src/app
    entrypoint: ["npm", "run", "compose:start"]
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://backend:4000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 20

  frontend:
    container_name: frontend
    image: node:12.2-alpine
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
      - "${FRONTEND_PORT_WS:-35729}:35729"

    volumes:
      - ./docker-data/frontend/node_modules:/usr/src/app/node_modules:cached
      - ./frontend/package.json:/usr/src/app/package.json:delegated
      - ./frontend/package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./frontend/public:/usr/src/app/public:delegated
      - ./frontend/src:/usr/src/app/src:delegated
    environment:
      REACT_APP_HASURA_URL: http://localhost:8080
      CHOKIDAR_USEPOLLING: "true"
    working_dir: /usr/src/app
    entrypoint: ["npm", "run", "compose:start"]
    stdin_open: true
    tty: true

  ###
  ### UTILITIES
  ###

  migrations:
    container_name: migrations
    build: ./migrations
    depends_on:
      hasura:
        condition: service_healthy
    volumes:
      - ./migrations/metadata:/metadata:cached
      - ./migrations/migrations:/migrations:cached
      - ./migrations/seeds:/seeds:cached
    environment:
      HASURA_ENDPOINT: http://hasura:8080
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    stdin_open: true
    tty: true

  ###
  ### INFRASTRUCTURE
  ###

  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v1.3.0
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
      - "${HASURA_PORT:-8080}:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "gitpod-hasura-demo"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "h2leOvdgjwpV0As5L8rZlV3VDVOsOmwk"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      EVT_TODOS_CAPITALIZE_URL: http://backend:4000
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://hasura:8080/healthz"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    container_name: adminer
    image: adminer:4.7
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:db
    ports:
      - "${ADMINER_PORT:-8081}:8080"

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - ./docker-data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
